title: Research Portfolio
description: Computational biologist with diverse experience analyzing, visualizing, and communicating biological data. Interested in biology, geology, and ecology. Adaptable, creative, insightful.
email: dylangagler@gmail.com
logo: MeWithNet.png
theme: jekyll-theme-minimal
