title: Research Portfolio
description: Interdisciplinary natural scientist with extensive bioinformatic and field experience. Broadly interested in being broadly interested. 
email: dylangagler@gmail.com
logo: Me_Norway.jpg
theme: jekyll-theme-minimal
