title: Dylan C. Gagler
description: Interdisciplinary natural scientist with extensive bioinformatic and field experience. Peer reviewed publications in astrobiology and cancer biology. Incoming PhD student at the AMNH interested in photosymbioses in sacoglossan sea slugs. [Google Scholar](https://scholar.google.com/citations?user=6l3aYEoAAAAJ&hl=en&oi=sra)
email: dylangagler@gmail.com
logo: Me_Norway.jpg
theme: jekyll-theme-minimal
