theme: jekyll-theme-minimal

## About Me
Description: I'm a Master's student at Arizona State University, studying astrobiology under Dr. Sara Imari Walker. My research involves accumulating large amounts of genetic and biochemical data for microorganisms to uncover large scale patterns in biochemistry, specifically enzyme usage. My previous work involved geochemical and microbiological fieldwork in Yellowstone National Park, where I collected samples for subsequent laboratory analysis. Outside of research, I love to explore nature, read, and spend time with the people I care about.
