title: Dylan C. Gagler
description: [Google Scholar](https://scholar.google.com/citations?user=6l3aYEoAAAAJ&hl=en&oi=sra) | [CV](https://github.com/dgagler/dgagler/blob/master/dgagler_CV_2024.pdf) | [LinkedIn](https://www.linkedin.com/in/dylan-gagler-4a0a68191/) 
email: dylangagler@gmail.com
logo: Me_Norway.jpg
theme: jekyll-theme-minimal
