title: Minimal theme
description: [CV](https://github.com/dgagler/dgagler/blob/master/dgagler_CV.pdf) 

[LinkedIn](https://www.linkedin.com/in/dylan-gagler-4a0a68191/) 
google_analytics:
theme: jekyll-theme-minimal
