title: Dylan C. Gagler
description: Interdisciplinary natural scientist. Incoming PhD student @ AMNH
email: dylangagler@gmail.com
logo: Me_Norway.jpg
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
