title: Research Portfolio
description: Interdisciplinary natural scientist with extensive bioinformatic and field experience. Peer reviewed publications in astrobiology and cancer biology. 

MS in Geological Sciences, with a focus in astrobiology
BS in Geology with Anthropology minor

[Google Scholar](https://scholar.google.com/citations?user=6l3aYEoAAAAJ&hl=en&oi=sra)
email: dylangagler@gmail.com
logo: Me_Norway.jpg
theme: jekyll-theme-minimal
